package heaven.bonree.protobuf.tasks;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_MBTaskResult.proto

public final class PBMBTaskResult {
  private PBMBTaskResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PB_MBTaskResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .PB_MBTaskNavigateResult navigateResult = 1;
    java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult> 
        getNavigateResultList();
    PBMBTaskNavigateResult.PB_MBTaskNavigateResult getNavigateResult(int index);
    int getNavigateResultCount();
    java.util.List<? extends PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder> 
        getNavigateResultOrBuilderList();
    PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder getNavigateResultOrBuilder(
        int index);
    
    // repeated .PB_MBTaskNetenvResult netenvResult = 2;
    java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult> 
        getNetenvResultList();
    PBMBTaskNetenvResult.PB_MBTaskNetenvResult getNetenvResult(int index);
    int getNetenvResultCount();
    java.util.List<? extends PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder> 
        getNetenvResultOrBuilderList();
    PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder getNetenvResultOrBuilder(
        int index);
  }
  public static final class PB_MBTaskResult extends
      com.google.protobuf.GeneratedMessage
      implements PB_MBTaskResultOrBuilder {
    // Use PB_MBTaskResult.newBuilder() to construct.
    private PB_MBTaskResult(Builder builder) {
      super(builder);
    }
    private PB_MBTaskResult(boolean noInit) {}
    
    private static final PB_MBTaskResult defaultInstance;
    public static PB_MBTaskResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public PB_MBTaskResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBMBTaskResult.internal_static_PB_MBTaskResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBMBTaskResult.internal_static_PB_MBTaskResult_fieldAccessorTable;
    }
    
    // repeated .PB_MBTaskNavigateResult navigateResult = 1;
    public static final int NAVIGATERESULT_FIELD_NUMBER = 1;
    private java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult> navigateResult_;
    public java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult> getNavigateResultList() {
      return navigateResult_;
    }
    public java.util.List<? extends PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder> 
        getNavigateResultOrBuilderList() {
      return navigateResult_;
    }
    public int getNavigateResultCount() {
      return navigateResult_.size();
    }
    public PBMBTaskNavigateResult.PB_MBTaskNavigateResult getNavigateResult(int index) {
      return navigateResult_.get(index);
    }
    public PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder getNavigateResultOrBuilder(
        int index) {
      return navigateResult_.get(index);
    }
    
    // repeated .PB_MBTaskNetenvResult netenvResult = 2;
    public static final int NETENVRESULT_FIELD_NUMBER = 2;
    private java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult> netenvResult_;
    public java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult> getNetenvResultList() {
      return netenvResult_;
    }
    public java.util.List<? extends PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder> 
        getNetenvResultOrBuilderList() {
      return netenvResult_;
    }
    public int getNetenvResultCount() {
      return netenvResult_.size();
    }
    public PBMBTaskNetenvResult.PB_MBTaskNetenvResult getNetenvResult(int index) {
      return netenvResult_.get(index);
    }
    public PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder getNetenvResultOrBuilder(
        int index) {
      return netenvResult_.get(index);
    }
    
    private void initFields() {
      navigateResult_ = java.util.Collections.emptyList();
      netenvResult_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < navigateResult_.size(); i++) {
        output.writeMessage(1, navigateResult_.get(i));
      }
      for (int i = 0; i < netenvResult_.size(); i++) {
        output.writeMessage(2, netenvResult_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < navigateResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, navigateResult_.get(i));
      }
      for (int i = 0; i < netenvResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, netenvResult_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static PBMBTaskResult.PB_MBTaskResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static PBMBTaskResult.PB_MBTaskResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PBMBTaskResult.PB_MBTaskResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PBMBTaskResult.PB_MBTaskResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBMBTaskResult.internal_static_PB_MBTaskResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBMBTaskResult.internal_static_PB_MBTaskResult_fieldAccessorTable;
      }
      
      // Construct using PBMBTaskResult.PB_MBTaskResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNavigateResultFieldBuilder();
          getNetenvResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (navigateResultBuilder_ == null) {
          navigateResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          navigateResultBuilder_.clear();
        }
        if (netenvResultBuilder_ == null) {
          netenvResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          netenvResultBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBMBTaskResult.PB_MBTaskResult.getDescriptor();
      }
      
      public PBMBTaskResult.PB_MBTaskResult getDefaultInstanceForType() {
        return PBMBTaskResult.PB_MBTaskResult.getDefaultInstance();
      }
      
      public PBMBTaskResult.PB_MBTaskResult build() {
        PBMBTaskResult.PB_MBTaskResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private PBMBTaskResult.PB_MBTaskResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        PBMBTaskResult.PB_MBTaskResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public PBMBTaskResult.PB_MBTaskResult buildPartial() {
        PBMBTaskResult.PB_MBTaskResult result = new PBMBTaskResult.PB_MBTaskResult(this);
        int from_bitField0_ = bitField0_;
        if (navigateResultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            navigateResult_ = java.util.Collections.unmodifiableList(navigateResult_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.navigateResult_ = navigateResult_;
        } else {
          result.navigateResult_ = navigateResultBuilder_.build();
        }
        if (netenvResultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            netenvResult_ = java.util.Collections.unmodifiableList(netenvResult_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.netenvResult_ = netenvResult_;
        } else {
          result.netenvResult_ = netenvResultBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBMBTaskResult.PB_MBTaskResult) {
          return mergeFrom((PBMBTaskResult.PB_MBTaskResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(PBMBTaskResult.PB_MBTaskResult other) {
        if (other == PBMBTaskResult.PB_MBTaskResult.getDefaultInstance()) return this;
        if (navigateResultBuilder_ == null) {
          if (!other.navigateResult_.isEmpty()) {
            if (navigateResult_.isEmpty()) {
              navigateResult_ = other.navigateResult_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNavigateResultIsMutable();
              navigateResult_.addAll(other.navigateResult_);
            }
            onChanged();
          }
        } else {
          if (!other.navigateResult_.isEmpty()) {
            if (navigateResultBuilder_.isEmpty()) {
              navigateResultBuilder_.dispose();
              navigateResultBuilder_ = null;
              navigateResult_ = other.navigateResult_;
              bitField0_ = (bitField0_ & ~0x00000001);
              navigateResultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNavigateResultFieldBuilder() : null;
            } else {
              navigateResultBuilder_.addAllMessages(other.navigateResult_);
            }
          }
        }
        if (netenvResultBuilder_ == null) {
          if (!other.netenvResult_.isEmpty()) {
            if (netenvResult_.isEmpty()) {
              netenvResult_ = other.netenvResult_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNetenvResultIsMutable();
              netenvResult_.addAll(other.netenvResult_);
            }
            onChanged();
          }
        } else {
          if (!other.netenvResult_.isEmpty()) {
            if (netenvResultBuilder_.isEmpty()) {
              netenvResultBuilder_.dispose();
              netenvResultBuilder_ = null;
              netenvResult_ = other.netenvResult_;
              bitField0_ = (bitField0_ & ~0x00000002);
              netenvResultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNetenvResultFieldBuilder() : null;
            } else {
              netenvResultBuilder_.addAllMessages(other.netenvResult_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder subBuilder = PBMBTaskNavigateResult.PB_MBTaskNavigateResult.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNavigateResult(subBuilder.buildPartial());
              break;
            }
            case 18: {
              PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder subBuilder = PBMBTaskNetenvResult.PB_MBTaskNetenvResult.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNetenvResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .PB_MBTaskNavigateResult navigateResult = 1;
      private java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult> navigateResult_ =
        java.util.Collections.emptyList();
      private void ensureNavigateResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          navigateResult_ = new java.util.ArrayList<PBMBTaskNavigateResult.PB_MBTaskNavigateResult>(navigateResult_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          PBMBTaskNavigateResult.PB_MBTaskNavigateResult, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder, PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder> navigateResultBuilder_;
      
      public java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult> getNavigateResultList() {
        if (navigateResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(navigateResult_);
        } else {
          return navigateResultBuilder_.getMessageList();
        }
      }
      public int getNavigateResultCount() {
        if (navigateResultBuilder_ == null) {
          return navigateResult_.size();
        } else {
          return navigateResultBuilder_.getCount();
        }
      }
      public PBMBTaskNavigateResult.PB_MBTaskNavigateResult getNavigateResult(int index) {
        if (navigateResultBuilder_ == null) {
          return navigateResult_.get(index);
        } else {
          return navigateResultBuilder_.getMessage(index);
        }
      }
      public Builder setNavigateResult(
          int index, PBMBTaskNavigateResult.PB_MBTaskNavigateResult value) {
        if (navigateResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNavigateResultIsMutable();
          navigateResult_.set(index, value);
          onChanged();
        } else {
          navigateResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNavigateResult(
          int index, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder builderForValue) {
        if (navigateResultBuilder_ == null) {
          ensureNavigateResultIsMutable();
          navigateResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          navigateResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNavigateResult(PBMBTaskNavigateResult.PB_MBTaskNavigateResult value) {
        if (navigateResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNavigateResultIsMutable();
          navigateResult_.add(value);
          onChanged();
        } else {
          navigateResultBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNavigateResult(
          int index, PBMBTaskNavigateResult.PB_MBTaskNavigateResult value) {
        if (navigateResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNavigateResultIsMutable();
          navigateResult_.add(index, value);
          onChanged();
        } else {
          navigateResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNavigateResult(
          PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder builderForValue) {
        if (navigateResultBuilder_ == null) {
          ensureNavigateResultIsMutable();
          navigateResult_.add(builderForValue.build());
          onChanged();
        } else {
          navigateResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNavigateResult(
          int index, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder builderForValue) {
        if (navigateResultBuilder_ == null) {
          ensureNavigateResultIsMutable();
          navigateResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          navigateResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNavigateResult(
          java.lang.Iterable<? extends PBMBTaskNavigateResult.PB_MBTaskNavigateResult> values) {
        if (navigateResultBuilder_ == null) {
          ensureNavigateResultIsMutable();
          super.addAll(values, navigateResult_);
          onChanged();
        } else {
          navigateResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNavigateResult() {
        if (navigateResultBuilder_ == null) {
          navigateResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          navigateResultBuilder_.clear();
        }
        return this;
      }
      public Builder removeNavigateResult(int index) {
        if (navigateResultBuilder_ == null) {
          ensureNavigateResultIsMutable();
          navigateResult_.remove(index);
          onChanged();
        } else {
          navigateResultBuilder_.remove(index);
        }
        return this;
      }
      public PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder getNavigateResultBuilder(
          int index) {
        return getNavigateResultFieldBuilder().getBuilder(index);
      }
      public PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder getNavigateResultOrBuilder(
          int index) {
        if (navigateResultBuilder_ == null) {
          return navigateResult_.get(index);  } else {
          return navigateResultBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder> 
           getNavigateResultOrBuilderList() {
        if (navigateResultBuilder_ != null) {
          return navigateResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(navigateResult_);
        }
      }
      public PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder addNavigateResultBuilder() {
        return getNavigateResultFieldBuilder().addBuilder(
            PBMBTaskNavigateResult.PB_MBTaskNavigateResult.getDefaultInstance());
      }
      public PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder addNavigateResultBuilder(
          int index) {
        return getNavigateResultFieldBuilder().addBuilder(
            index, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.getDefaultInstance());
      }
      public java.util.List<PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder> 
           getNavigateResultBuilderList() {
        return getNavigateResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PBMBTaskNavigateResult.PB_MBTaskNavigateResult, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder, PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder> 
          getNavigateResultFieldBuilder() {
        if (navigateResultBuilder_ == null) {
          navigateResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PBMBTaskNavigateResult.PB_MBTaskNavigateResult, PBMBTaskNavigateResult.PB_MBTaskNavigateResult.Builder, PBMBTaskNavigateResult.PB_MBTaskNavigateResultOrBuilder>(
                  navigateResult_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          navigateResult_ = null;
        }
        return navigateResultBuilder_;
      }
      
      // repeated .PB_MBTaskNetenvResult netenvResult = 2;
      private java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult> netenvResult_ =
        java.util.Collections.emptyList();
      private void ensureNetenvResultIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          netenvResult_ = new java.util.ArrayList<PBMBTaskNetenvResult.PB_MBTaskNetenvResult>(netenvResult_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          PBMBTaskNetenvResult.PB_MBTaskNetenvResult, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder, PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder> netenvResultBuilder_;
      
      public java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult> getNetenvResultList() {
        if (netenvResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(netenvResult_);
        } else {
          return netenvResultBuilder_.getMessageList();
        }
      }
      public int getNetenvResultCount() {
        if (netenvResultBuilder_ == null) {
          return netenvResult_.size();
        } else {
          return netenvResultBuilder_.getCount();
        }
      }
      public PBMBTaskNetenvResult.PB_MBTaskNetenvResult getNetenvResult(int index) {
        if (netenvResultBuilder_ == null) {
          return netenvResult_.get(index);
        } else {
          return netenvResultBuilder_.getMessage(index);
        }
      }
      public Builder setNetenvResult(
          int index, PBMBTaskNetenvResult.PB_MBTaskNetenvResult value) {
        if (netenvResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetenvResultIsMutable();
          netenvResult_.set(index, value);
          onChanged();
        } else {
          netenvResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNetenvResult(
          int index, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder builderForValue) {
        if (netenvResultBuilder_ == null) {
          ensureNetenvResultIsMutable();
          netenvResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          netenvResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNetenvResult(PBMBTaskNetenvResult.PB_MBTaskNetenvResult value) {
        if (netenvResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetenvResultIsMutable();
          netenvResult_.add(value);
          onChanged();
        } else {
          netenvResultBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNetenvResult(
          int index, PBMBTaskNetenvResult.PB_MBTaskNetenvResult value) {
        if (netenvResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNetenvResultIsMutable();
          netenvResult_.add(index, value);
          onChanged();
        } else {
          netenvResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNetenvResult(
          PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder builderForValue) {
        if (netenvResultBuilder_ == null) {
          ensureNetenvResultIsMutable();
          netenvResult_.add(builderForValue.build());
          onChanged();
        } else {
          netenvResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNetenvResult(
          int index, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder builderForValue) {
        if (netenvResultBuilder_ == null) {
          ensureNetenvResultIsMutable();
          netenvResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          netenvResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNetenvResult(
          java.lang.Iterable<? extends PBMBTaskNetenvResult.PB_MBTaskNetenvResult> values) {
        if (netenvResultBuilder_ == null) {
          ensureNetenvResultIsMutable();
          super.addAll(values, netenvResult_);
          onChanged();
        } else {
          netenvResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNetenvResult() {
        if (netenvResultBuilder_ == null) {
          netenvResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          netenvResultBuilder_.clear();
        }
        return this;
      }
      public Builder removeNetenvResult(int index) {
        if (netenvResultBuilder_ == null) {
          ensureNetenvResultIsMutable();
          netenvResult_.remove(index);
          onChanged();
        } else {
          netenvResultBuilder_.remove(index);
        }
        return this;
      }
      public PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder getNetenvResultBuilder(
          int index) {
        return getNetenvResultFieldBuilder().getBuilder(index);
      }
      public PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder getNetenvResultOrBuilder(
          int index) {
        if (netenvResultBuilder_ == null) {
          return netenvResult_.get(index);  } else {
          return netenvResultBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder> 
           getNetenvResultOrBuilderList() {
        if (netenvResultBuilder_ != null) {
          return netenvResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(netenvResult_);
        }
      }
      public PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder addNetenvResultBuilder() {
        return getNetenvResultFieldBuilder().addBuilder(
            PBMBTaskNetenvResult.PB_MBTaskNetenvResult.getDefaultInstance());
      }
      public PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder addNetenvResultBuilder(
          int index) {
        return getNetenvResultFieldBuilder().addBuilder(
            index, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.getDefaultInstance());
      }
      public java.util.List<PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder> 
           getNetenvResultBuilderList() {
        return getNetenvResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PBMBTaskNetenvResult.PB_MBTaskNetenvResult, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder, PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder> 
          getNetenvResultFieldBuilder() {
        if (netenvResultBuilder_ == null) {
          netenvResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PBMBTaskNetenvResult.PB_MBTaskNetenvResult, PBMBTaskNetenvResult.PB_MBTaskNetenvResult.Builder, PBMBTaskNetenvResult.PB_MBTaskNetenvResultOrBuilder>(
                  netenvResult_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          netenvResult_ = null;
        }
        return netenvResultBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:PB_MBTaskResult)
    }
    
    static {
      defaultInstance = new PB_MBTaskResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PB_MBTaskResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_MBTaskResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PB_MBTaskResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025PB_MBTaskResult.proto\032\035PB_MBTaskNaviga" +
      "teResult.proto\032\033PB_MBTaskNetenvResult.pr" +
      "oto\"q\n\017PB_MBTaskResult\0220\n\016navigateResult" +
      "\030\001 \003(\0132\030.PB_MBTaskNavigateResult\022,\n\014nete" +
      "nvResult\030\002 \003(\0132\026.PB_MBTaskNetenvResult"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PB_MBTaskResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PB_MBTaskResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PB_MBTaskResult_descriptor,
              new java.lang.String[] { "NavigateResult", "NetenvResult", },
              PBMBTaskResult.PB_MBTaskResult.class,
              PBMBTaskResult.PB_MBTaskResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PBMBTaskNavigateResult.getDescriptor(),
          PBMBTaskNetenvResult.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
