package heaven.bonree.protobuf.tasks;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_TaskRequest.proto

public final class PBTaskRequest {
  private PBTaskRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PB_TaskRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string taskType = 1;
    java.util.List<String> getTaskTypeList();
    int getTaskTypeCount();
    String getTaskType(int index);
    
    // required string username = 2;
    boolean hasUsername();
    String getUsername();
    
    // required string pwd = 3;
    boolean hasPwd();
    String getPwd();
    
    // repeated string taskId = 4;
    java.util.List<String> getTaskIdList();
    int getTaskIdCount();
    String getTaskId(int index);
  }
  public static final class PB_TaskRequest extends
      com.google.protobuf.GeneratedMessage
      implements PB_TaskRequestOrBuilder {
    // Use PB_TaskRequest.newBuilder() to construct.
    private PB_TaskRequest(Builder builder) {
      super(builder);
    }
    private PB_TaskRequest(boolean noInit) {}
    
    private static final PB_TaskRequest defaultInstance;
    public static PB_TaskRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PB_TaskRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PBTaskRequest.internal_static_PB_TaskRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PBTaskRequest.internal_static_PB_TaskRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string taskType = 1;
    public static final int TASKTYPE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList taskType_;
    public java.util.List<String>
        getTaskTypeList() {
      return taskType_;
    }
    public int getTaskTypeCount() {
      return taskType_.size();
    }
    public String getTaskType(int index) {
      return taskType_.get(index);
    }
    
    // required string username = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string pwd = 3;
    public static final int PWD_FIELD_NUMBER = 3;
    private java.lang.Object pwd_;
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string taskId = 4;
    public static final int TASKID_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList taskId_;
    public java.util.List<String>
        getTaskIdList() {
      return taskId_;
    }
    public int getTaskIdCount() {
      return taskId_.size();
    }
    public String getTaskId(int index) {
      return taskId_.get(index);
    }
    
    private void initFields() {
      taskType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      username_ = "";
      pwd_ = "";
      taskId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < taskType_.size(); i++) {
        output.writeBytes(1, taskType_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getPwdBytes());
      }
      for (int i = 0; i < taskId_.size(); i++) {
        output.writeBytes(4, taskId_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < taskType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(taskType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTaskTypeList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPwdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < taskId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(taskId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTaskIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static PBTaskRequest.PB_TaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static PBTaskRequest.PB_TaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PBTaskRequest.PB_TaskRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PBTaskRequest.PB_TaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PBTaskRequest.internal_static_PB_TaskRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PBTaskRequest.internal_static_PB_TaskRequest_fieldAccessorTable;
      }
      
      // Construct using PBTaskRequest.PB_TaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        taskType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        taskId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PBTaskRequest.PB_TaskRequest.getDescriptor();
      }
      
      public PBTaskRequest.PB_TaskRequest getDefaultInstanceForType() {
        return PBTaskRequest.PB_TaskRequest.getDefaultInstance();
      }
      
      public PBTaskRequest.PB_TaskRequest build() {
        PBTaskRequest.PB_TaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private PBTaskRequest.PB_TaskRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        PBTaskRequest.PB_TaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public PBTaskRequest.PB_TaskRequest buildPartial() {
        PBTaskRequest.PB_TaskRequest result = new PBTaskRequest.PB_TaskRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          taskType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              taskType_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.taskType_ = taskType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pwd_ = pwd_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          taskId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              taskId_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.taskId_ = taskId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PBTaskRequest.PB_TaskRequest) {
          return mergeFrom((PBTaskRequest.PB_TaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(PBTaskRequest.PB_TaskRequest other) {
        if (other == PBTaskRequest.PB_TaskRequest.getDefaultInstance()) return this;
        if (!other.taskType_.isEmpty()) {
          if (taskType_.isEmpty()) {
            taskType_ = other.taskType_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTaskTypeIsMutable();
            taskType_.addAll(other.taskType_);
          }
          onChanged();
        }
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPwd()) {
          setPwd(other.getPwd());
        }
        if (!other.taskId_.isEmpty()) {
          if (taskId_.isEmpty()) {
            taskId_ = other.taskId_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTaskIdIsMutable();
            taskId_.addAll(other.taskId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPwd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureTaskTypeIsMutable();
              taskType_.add(input.readBytes());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              username_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pwd_ = input.readBytes();
              break;
            }
            case 34: {
              ensureTaskIdIsMutable();
              taskId_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string taskType = 1;
      private com.google.protobuf.LazyStringList taskType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTaskTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          taskType_ = new com.google.protobuf.LazyStringArrayList(taskType_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getTaskTypeList() {
        return java.util.Collections.unmodifiableList(taskType_);
      }
      public int getTaskTypeCount() {
        return taskType_.size();
      }
      public String getTaskType(int index) {
        return taskType_.get(index);
      }
      public Builder setTaskType(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaskTypeIsMutable();
        taskType_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addTaskType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaskTypeIsMutable();
        taskType_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllTaskType(
          java.lang.Iterable<String> values) {
        ensureTaskTypeIsMutable();
        super.addAll(values, taskType_);
        onChanged();
        return this;
      }
      public Builder clearTaskType() {
        taskType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addTaskType(com.google.protobuf.ByteString value) {
        ensureTaskTypeIsMutable();
        taskType_.add(value);
        onChanged();
      }
      
      // required string username = 2;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        username_ = value;
        onChanged();
      }
      
      // required string pwd = 3;
      private java.lang.Object pwd_ = "";
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      void setPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
      }
      
      // repeated string taskId = 4;
      private com.google.protobuf.LazyStringList taskId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTaskIdIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          taskId_ = new com.google.protobuf.LazyStringArrayList(taskId_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getTaskIdList() {
        return java.util.Collections.unmodifiableList(taskId_);
      }
      public int getTaskIdCount() {
        return taskId_.size();
      }
      public String getTaskId(int index) {
        return taskId_.get(index);
      }
      public Builder setTaskId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaskIdIsMutable();
        taskId_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addTaskId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaskIdIsMutable();
        taskId_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllTaskId(
          java.lang.Iterable<String> values) {
        ensureTaskIdIsMutable();
        super.addAll(values, taskId_);
        onChanged();
        return this;
      }
      public Builder clearTaskId() {
        taskId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addTaskId(com.google.protobuf.ByteString value) {
        ensureTaskIdIsMutable();
        taskId_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PB_TaskRequest)
    }
    
    static {
      defaultInstance = new PB_TaskRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PB_TaskRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PB_TaskRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PB_TaskRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PB_TaskRequest.proto\"Q\n\016PB_TaskRequest" +
      "\022\020\n\010taskType\030\001 \003(\t\022\020\n\010username\030\002 \002(\t\022\013\n\003" +
      "pwd\030\003 \002(\t\022\016\n\006taskId\030\004 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PB_TaskRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PB_TaskRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PB_TaskRequest_descriptor,
              new java.lang.String[] { "TaskType", "Username", "Pwd", "TaskId", },
              PBTaskRequest.PB_TaskRequest.class,
              PBTaskRequest.PB_TaskRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
